[package]
name = "api-challenge"
version = "0.1.0"
authors = ["Gary Mansell <gary.mansell@cyberlytic.com>"]

[dependencies]
rocket = "0.3.14"
rocket_codegen = "0.3.14"
bson = "0.10.0"
mongodb = "0.3.7"